"""Added flagged to posts.

Revision ID: 65891fe623dd
Revises: 6ce918b8e805
Create Date: 2024-11-12 22:12:19.004969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65891fe623dd'
down_revision = '6ce918b8e805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    # ### end Alembic commands ###
